### ISSUE TITLE
Allow user to select a single metric to return

### ISSUE THREAD

**Issue by memosstilvi** [msempere/hal9001#1]
Right now the bot returns all the metrics and there is no way the user can only select a single metric to view.

It would be helpful for the users to be able to view metrics on isolation, for example:

`rds aa1gf7voez5f3zp CPUUtilization`

If no specific metric is provided, we can default to returning all the metrics.

**Comment by msempere** [comment]
Enhancement added: 7272c6b28717723384d1d45320702f5f6d84aa11
